# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.30.5/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.30.5/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/c2/Documents/BrainEngine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/c2/Documents/BrainEngine/BrainEngine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.30.5/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.30.5/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/c2/Documents/BrainEngine/BrainEngine/CMakeFiles /Users/c2/Documents/BrainEngine/BrainEngine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/c2/Documents/BrainEngine/BrainEngine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /Users/c2/Documents/BrainEngine/BrainEngine/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Brain

# Build rule for target.
Brain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Brain
.PHONY : Brain

# fast build rule for target.
Brain/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/build
.PHONY : Brain/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f BrainEngine/Dependencies/glfw-3.3.2/src/CMakeFiles/glfw.dir/build.make BrainEngine/Dependencies/glfw-3.3.2/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f BrainEngine/Dependencies/glad/CMakeFiles/glad.dir/build.make BrainEngine/Dependencies/glad/CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named stb_image

# Build rule for target.
stb_image: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stb_image
.PHONY : stb_image

# fast build rule for target.
stb_image/fast:
	$(MAKE) $(MAKESILENT) -f BrainEngine/Dependencies/stb_image/CMakeFiles/stb_image.dir/build.make BrainEngine/Dependencies/stb_image/CMakeFiles/stb_image.dir/build
.PHONY : stb_image/fast

#=============================================================================
# Target rules for targets named stb_truetype

# Build rule for target.
stb_truetype: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stb_truetype
.PHONY : stb_truetype

# fast build rule for target.
stb_truetype/fast:
	$(MAKE) $(MAKESILENT) -f BrainEngine/Dependencies/stb_truetype/CMakeFiles/stb_truetype.dir/build.make BrainEngine/Dependencies/stb_truetype/CMakeFiles/stb_truetype.dir/build
.PHONY : stb_truetype/fast

#=============================================================================
# Target rules for targets named raudio

# Build rule for target.
raudio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raudio
.PHONY : raudio

# fast build rule for target.
raudio/fast:
	$(MAKE) $(MAKESILENT) -f BrainEngine/Dependencies/raudio/CMakeFiles/raudio.dir/build.make BrainEngine/Dependencies/raudio/CMakeFiles/raudio.dir/build
.PHONY : raudio/fast

#=============================================================================
# Target rules for targets named glm

# Build rule for target.
glm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glm
.PHONY : glm

# fast build rule for target.
glm/fast:
	$(MAKE) $(MAKESILENT) -f BrainEngine/Dependencies/glm/glm/CMakeFiles/glm.dir/build.make BrainEngine/Dependencies/glm/glm/CMakeFiles/glm.dir/build
.PHONY : glm/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f BrainEngine/Dependencies/imgui-docking/CMakeFiles/imgui.dir/build.make BrainEngine/Dependencies/imgui-docking/CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named safeSave

# Build rule for target.
safeSave: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 safeSave
.PHONY : safeSave

# fast build rule for target.
safeSave/fast:
	$(MAKE) $(MAKESILENT) -f BrainEngine/Dependencies/safeSave/CMakeFiles/safeSave.dir/build.make BrainEngine/Dependencies/safeSave/CMakeFiles/safeSave.dir/build
.PHONY : safeSave/fast

#=============================================================================
# Target rules for targets named gl2d

# Build rule for target.
gl2d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gl2d
.PHONY : gl2d

# fast build rule for target.
gl2d/fast:
	$(MAKE) $(MAKESILENT) -f BrainEngine/Dependencies/gl2d/CMakeFiles/gl2d.dir/build.make BrainEngine/Dependencies/gl2d/CMakeFiles/gl2d.dir/build
.PHONY : gl2d/fast

#=============================================================================
# Target rules for targets named glui

# Build rule for target.
glui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glui
.PHONY : glui

# fast build rule for target.
glui/fast:
	$(MAKE) $(MAKESILENT) -f BrainEngine/Dependencies/glui/CMakeFiles/glui.dir/build.make BrainEngine/Dependencies/glui/CMakeFiles/glui.dir/build
.PHONY : glui/fast

src/gameLayer/gameLayer.o: src/gameLayer/gameLayer.cpp.o
.PHONY : src/gameLayer/gameLayer.o

# target to build an object file
src/gameLayer/gameLayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/gameLayer/gameLayer.cpp.o
.PHONY : src/gameLayer/gameLayer.cpp.o

src/gameLayer/gameLayer.i: src/gameLayer/gameLayer.cpp.i
.PHONY : src/gameLayer/gameLayer.i

# target to preprocess a source file
src/gameLayer/gameLayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/gameLayer/gameLayer.cpp.i
.PHONY : src/gameLayer/gameLayer.cpp.i

src/gameLayer/gameLayer.s: src/gameLayer/gameLayer.cpp.s
.PHONY : src/gameLayer/gameLayer.s

# target to generate assembly for a file
src/gameLayer/gameLayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/gameLayer/gameLayer.cpp.s
.PHONY : src/gameLayer/gameLayer.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/platform/errorReporting.o: src/platform/errorReporting.cpp.o
.PHONY : src/platform/errorReporting.o

# target to build an object file
src/platform/errorReporting.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/platform/errorReporting.cpp.o
.PHONY : src/platform/errorReporting.cpp.o

src/platform/errorReporting.i: src/platform/errorReporting.cpp.i
.PHONY : src/platform/errorReporting.i

# target to preprocess a source file
src/platform/errorReporting.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/platform/errorReporting.cpp.i
.PHONY : src/platform/errorReporting.cpp.i

src/platform/errorReporting.s: src/platform/errorReporting.cpp.s
.PHONY : src/platform/errorReporting.s

# target to generate assembly for a file
src/platform/errorReporting.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/platform/errorReporting.cpp.s
.PHONY : src/platform/errorReporting.cpp.s

src/platform/opterPlatformFunctions.o: src/platform/opterPlatformFunctions.cpp.o
.PHONY : src/platform/opterPlatformFunctions.o

# target to build an object file
src/platform/opterPlatformFunctions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/platform/opterPlatformFunctions.cpp.o
.PHONY : src/platform/opterPlatformFunctions.cpp.o

src/platform/opterPlatformFunctions.i: src/platform/opterPlatformFunctions.cpp.i
.PHONY : src/platform/opterPlatformFunctions.i

# target to preprocess a source file
src/platform/opterPlatformFunctions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/platform/opterPlatformFunctions.cpp.i
.PHONY : src/platform/opterPlatformFunctions.cpp.i

src/platform/opterPlatformFunctions.s: src/platform/opterPlatformFunctions.cpp.s
.PHONY : src/platform/opterPlatformFunctions.s

# target to generate assembly for a file
src/platform/opterPlatformFunctions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/platform/opterPlatformFunctions.cpp.s
.PHONY : src/platform/opterPlatformFunctions.cpp.s

src/platform/platformInput.o: src/platform/platformInput.cpp.o
.PHONY : src/platform/platformInput.o

# target to build an object file
src/platform/platformInput.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/platform/platformInput.cpp.o
.PHONY : src/platform/platformInput.cpp.o

src/platform/platformInput.i: src/platform/platformInput.cpp.i
.PHONY : src/platform/platformInput.i

# target to preprocess a source file
src/platform/platformInput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/platform/platformInput.cpp.i
.PHONY : src/platform/platformInput.cpp.i

src/platform/platformInput.s: src/platform/platformInput.cpp.s
.PHONY : src/platform/platformInput.s

# target to generate assembly for a file
src/platform/platformInput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/platform/platformInput.cpp.s
.PHONY : src/platform/platformInput.cpp.s

src/vulkan/brain_device.o: src/vulkan/brain_device.cpp.o
.PHONY : src/vulkan/brain_device.o

# target to build an object file
src/vulkan/brain_device.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/vulkan/brain_device.cpp.o
.PHONY : src/vulkan/brain_device.cpp.o

src/vulkan/brain_device.i: src/vulkan/brain_device.cpp.i
.PHONY : src/vulkan/brain_device.i

# target to preprocess a source file
src/vulkan/brain_device.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/vulkan/brain_device.cpp.i
.PHONY : src/vulkan/brain_device.cpp.i

src/vulkan/brain_device.s: src/vulkan/brain_device.cpp.s
.PHONY : src/vulkan/brain_device.s

# target to generate assembly for a file
src/vulkan/brain_device.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/vulkan/brain_device.cpp.s
.PHONY : src/vulkan/brain_device.cpp.s

src/vulkan/brain_model.o: src/vulkan/brain_model.cpp.o
.PHONY : src/vulkan/brain_model.o

# target to build an object file
src/vulkan/brain_model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/vulkan/brain_model.cpp.o
.PHONY : src/vulkan/brain_model.cpp.o

src/vulkan/brain_model.i: src/vulkan/brain_model.cpp.i
.PHONY : src/vulkan/brain_model.i

# target to preprocess a source file
src/vulkan/brain_model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/vulkan/brain_model.cpp.i
.PHONY : src/vulkan/brain_model.cpp.i

src/vulkan/brain_model.s: src/vulkan/brain_model.cpp.s
.PHONY : src/vulkan/brain_model.s

# target to generate assembly for a file
src/vulkan/brain_model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/vulkan/brain_model.cpp.s
.PHONY : src/vulkan/brain_model.cpp.s

src/vulkan/brain_pipeline.o: src/vulkan/brain_pipeline.cpp.o
.PHONY : src/vulkan/brain_pipeline.o

# target to build an object file
src/vulkan/brain_pipeline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/vulkan/brain_pipeline.cpp.o
.PHONY : src/vulkan/brain_pipeline.cpp.o

src/vulkan/brain_pipeline.i: src/vulkan/brain_pipeline.cpp.i
.PHONY : src/vulkan/brain_pipeline.i

# target to preprocess a source file
src/vulkan/brain_pipeline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/vulkan/brain_pipeline.cpp.i
.PHONY : src/vulkan/brain_pipeline.cpp.i

src/vulkan/brain_pipeline.s: src/vulkan/brain_pipeline.cpp.s
.PHONY : src/vulkan/brain_pipeline.s

# target to generate assembly for a file
src/vulkan/brain_pipeline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/vulkan/brain_pipeline.cpp.s
.PHONY : src/vulkan/brain_pipeline.cpp.s

src/vulkan/brain_swap_chain.o: src/vulkan/brain_swap_chain.cpp.o
.PHONY : src/vulkan/brain_swap_chain.o

# target to build an object file
src/vulkan/brain_swap_chain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/vulkan/brain_swap_chain.cpp.o
.PHONY : src/vulkan/brain_swap_chain.cpp.o

src/vulkan/brain_swap_chain.i: src/vulkan/brain_swap_chain.cpp.i
.PHONY : src/vulkan/brain_swap_chain.i

# target to preprocess a source file
src/vulkan/brain_swap_chain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/vulkan/brain_swap_chain.cpp.i
.PHONY : src/vulkan/brain_swap_chain.cpp.i

src/vulkan/brain_swap_chain.s: src/vulkan/brain_swap_chain.cpp.s
.PHONY : src/vulkan/brain_swap_chain.s

# target to generate assembly for a file
src/vulkan/brain_swap_chain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/vulkan/brain_swap_chain.cpp.s
.PHONY : src/vulkan/brain_swap_chain.cpp.s

src/vulkan/brain_window.o: src/vulkan/brain_window.cpp.o
.PHONY : src/vulkan/brain_window.o

# target to build an object file
src/vulkan/brain_window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/vulkan/brain_window.cpp.o
.PHONY : src/vulkan/brain_window.cpp.o

src/vulkan/brain_window.i: src/vulkan/brain_window.cpp.i
.PHONY : src/vulkan/brain_window.i

# target to preprocess a source file
src/vulkan/brain_window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/vulkan/brain_window.cpp.i
.PHONY : src/vulkan/brain_window.cpp.i

src/vulkan/brain_window.s: src/vulkan/brain_window.cpp.s
.PHONY : src/vulkan/brain_window.s

# target to generate assembly for a file
src/vulkan/brain_window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/vulkan/brain_window.cpp.s
.PHONY : src/vulkan/brain_window.cpp.s

src/vulkan/first_app.o: src/vulkan/first_app.cpp.o
.PHONY : src/vulkan/first_app.o

# target to build an object file
src/vulkan/first_app.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/vulkan/first_app.cpp.o
.PHONY : src/vulkan/first_app.cpp.o

src/vulkan/first_app.i: src/vulkan/first_app.cpp.i
.PHONY : src/vulkan/first_app.i

# target to preprocess a source file
src/vulkan/first_app.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/vulkan/first_app.cpp.i
.PHONY : src/vulkan/first_app.cpp.i

src/vulkan/first_app.s: src/vulkan/first_app.cpp.s
.PHONY : src/vulkan/first_app.s

# target to generate assembly for a file
src/vulkan/first_app.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Brain.dir/build.make CMakeFiles/Brain.dir/src/vulkan/first_app.cpp.s
.PHONY : src/vulkan/first_app.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Brain"
	@echo "... gl2d"
	@echo "... glad"
	@echo "... glfw"
	@echo "... glm"
	@echo "... glui"
	@echo "... imgui"
	@echo "... raudio"
	@echo "... safeSave"
	@echo "... stb_image"
	@echo "... stb_truetype"
	@echo "... src/gameLayer/gameLayer.o"
	@echo "... src/gameLayer/gameLayer.i"
	@echo "... src/gameLayer/gameLayer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/platform/errorReporting.o"
	@echo "... src/platform/errorReporting.i"
	@echo "... src/platform/errorReporting.s"
	@echo "... src/platform/opterPlatformFunctions.o"
	@echo "... src/platform/opterPlatformFunctions.i"
	@echo "... src/platform/opterPlatformFunctions.s"
	@echo "... src/platform/platformInput.o"
	@echo "... src/platform/platformInput.i"
	@echo "... src/platform/platformInput.s"
	@echo "... src/vulkan/brain_device.o"
	@echo "... src/vulkan/brain_device.i"
	@echo "... src/vulkan/brain_device.s"
	@echo "... src/vulkan/brain_model.o"
	@echo "... src/vulkan/brain_model.i"
	@echo "... src/vulkan/brain_model.s"
	@echo "... src/vulkan/brain_pipeline.o"
	@echo "... src/vulkan/brain_pipeline.i"
	@echo "... src/vulkan/brain_pipeline.s"
	@echo "... src/vulkan/brain_swap_chain.o"
	@echo "... src/vulkan/brain_swap_chain.i"
	@echo "... src/vulkan/brain_swap_chain.s"
	@echo "... src/vulkan/brain_window.o"
	@echo "... src/vulkan/brain_window.i"
	@echo "... src/vulkan/brain_window.s"
	@echo "... src/vulkan/first_app.o"
	@echo "... src/vulkan/first_app.i"
	@echo "... src/vulkan/first_app.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /Users/c2/Documents/BrainEngine/BrainEngine/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

